# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10mwjAs9ZR_pmeNxsGUBiWVjg6x8Vc8hd
"""
# ran - rand
# plt - mtplt
import timeit as time
import random as rand
import matplotlib.pyplot as mtplt


# Insertion Sort
def insertion_sort(array):
    n= len(array);
    for ind in range(1, n):
        ele = array[ind]
        index = ind - 1
        while index >= 0:
            if array[index] > ele:
                array[index + 1] = array[index]
                index = index - 1
            else:
                break
        array[index + 1] = ele

# Selection Sort
def selection_sort(array):
     n= len(array)
     for start_ind in range(n):
        smallest_element=array[start_ind]
        ele_ind=start_ind
        for i in range(start_ind+1,n):
            if(array[i]<smallest_element):
                smallest_element=array[i]
                ele_ind=i
        # if(smallest_element!=array[start_ind]):
        array[start_ind],array[ele_ind]=array[ele_ind],array[start_ind]
        # else:break

# Bubble Sort
def bubble_sort(array):
    n= len(array)
    for ele1 in range(n):
        for ele in range(n-ele1-1):
            if(array[ele]>array[ele+1]):
                array[ele],array[ele+1]=array[ele+1],array[ele]

# Function to generate a random array of a given size
def generate_random(size):
    return [rand.randint(1, 1000) for _ in range(size)]

# Function to benchmark sorting algorithms
def benchmark(sort_func, array):
    n=len(array)
    setup_code = f"from __main__ import {sort_func}, generate_random; arr = generate_random({n})"
    stmt = f"{sort_func}(arr)"

    # Measure the execution time
    exe_time = time.timeit(stmt, setup=setup_code, number=10)

    return exe_time

# Benchmark parameters
sizes = [5, 10, 20, 50, 100, 200, 500, 1000,2000]  # Adjust as needed

# Results dictionary to store benchmark results
results = {'Insertion Sort': [], 'Selection Sort': [], 'Bubble Sort': []}

# Run benchmarks for each sorting algorithm and array size
for size in sizes:
    array = generate_random(size)

    # Insertion Sort
    ins_time = benchmark('insertion_sort', array)
    results['Insertion Sort'].append(ins_time)
    print(f"Input Size: {size}, Insertion Sort Execution Time: {ins_time:.6f} seconds")


    # Selection Sort
    sel_time = benchmark('sel_sort', array)
    results['Selection Sort'].append(sel_time)
    print(f"Input Size: {size}, Selection Sort Execution Time: {ins_time:.6f} seconds")

    # Bubble Sort
    bub_time = benchmark('bubble_sort', array)
    results['Bubble Sort'].append(bub_time)
    print(f"Input Size: {size}, Bubble Sort Execution Time: {ins_time:.6f} seconds")

# Plotting the results
mtplt.plot(sizes, results['Insertion Sort'], label='Insertion Sort', color='orange')
mtplt.plot(sizes, results['Selection Sort'], label='Selection Sort', color='blue')
mtplt.plot(sizes, results['Bubble Sort'], label='Bubble Sort', color='green')

mtplt.xlabel('Array Size')
mtplt.ylabel('Execution Time (sec)')
mtplt.title('Benchmark Sorting Algorithm')
mtplt.legend()
mtplt.show()